[build]
target = "./sim/web/index.html"
release = true
dist = "./target/dist"
public_url = "/"
filehash = true
inject_scripts = true

[watch]
watch = ["./sim", "./target/web", "./code", "./asm/src/std"]
ignore = []

[serve]
address = "127.0.0.1"
port = 3000

[clean]
dist = "./target/dist"
cargo = true

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["web", "code/boxes/switch"]
# command_arguments = [
#   "run",
#   "--bim",
#   "asm",
#   "--",
#   "-o",
#   "target/web/exec.bin",
#   "-i",
#   "code/boxes/switch",
# ]
