[build]
  target         = "./sim/web/index.html"
  release        = false
  dist           = "dist"
  public_url     = "/"
  filehash       = true
  inject_scripts = true

[watch]
  watch  = ["./sim", "./target/web.bin"]
  ignore = []

[serve]
  address       = "127.0.0.1"
  port          = 3000
  open          = true
  no_autoreload = false

[clean]
  dist  = "dist"
  cargo = true
