[package]
  name    = "sim"
  version = "0.1.0"
  edition = "2021"

  # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
  asm           = { path = "../asm" }
  typed-builder = "0.16"

[features]
  default    = ["syscontrol", "gfx"]
  syscontrol = []
  gfx        = []
