use phf::phf_map;

pub static STD: phf::Map<&'static str, &'static str> = phf_map! {
    "std" => include_str!("std/mod.asm"),
    "prelude" => include_str!("prelude/mod.asm"),
    "prelude::arch" => include_str!("prelude/arch.asm"),
    "prelude::macro" => include_str!("prelude/macro/mod.asm"),
    "prelude::macro::util" => include_str!("prelude/macro/util.asm"),
    "prelude::macro::math" => include_str!("prelude/macro/math/mod.asm"),
    "prelude::macro::math::add" => include_str!("prelude/macro/math/add.asm"),
    "prelude::macro::math::sub" => include_str!("prelude/macro/math/sub.asm"),
    "prelude::macro::call" => include_str!("prelude/macro/call.asm"),
    "prelude::macro::clear" => include_str!("prelude/macro/clear.asm"),
    "prelude::macro::jmp" => include_str!("prelude/macro/jmp.asm"),
    "prelude::macro::logic" => include_str!("prelude/macro/logic.asm"),
    "prelude::macro::send" => include_str!("prelude/macro/send.asm"),
    "std::math" => include_str!("std/math/mod.asm"),
    "std::math::mul" => include_str!("std/math/mul/mod.asm"),
    "std::math::mul::mul" => include_str!("std/math/mul/mul.asm"),
    "std::math::mul::mul16" => include_str!("std/math/mul/mul16.asm"),
    "std::math::shift" => include_str!("std/math/shift/mod.asm"),
    "std::math::shift::lsh" => include_str!("std/math/shift/lsh.asm"),
    "std::math::shift::lsh16" => include_str!("std/math/shift/lsh16.asm"),
    "std::math::shift::rsh" => include_str!("std/math/shift/rsh.asm"),
    "std::gfx" => include_str!("std/gfx/mod.asm"),
    "std::gfx::frame" => include_str!("std/gfx/frame.asm"),
    "std::wait" => include_str!("std/wait/mod.asm"),
};
